### ISSUE TITLE
Extrange shader don't work when activated

### ISSUE THREAD

**Issue by YeraX7** [nvb-uy/Hysteria#2]
### What happened?

I don't know exactly what the problem is but in a modpack with the distant horizons after a few times I have activated the shader with the default setting in balanced and the shader is not activated and I get this error code: 

```
dh_water.fsh: dh_water.fsh: 0(1310) : error C1503: undefined variable "dhDepthTex1"
0(1311) : error C1503: undefined variable "is_distant_horizons_terrain"
0(1312) : error C1503: undefined variable "dhProjectionInverse"

```

### Minecraft Version

1.20.2

### Which shader mod are you using?

Iris

### Shader mod version

1.1.0

### Shader settings

```conf
Default Balanced
```

### Relevant log output

```text
dh_water.fsh: dh_water.fsh: 0(1310) : error C1503: undefined variable "dhDepthTex1"
0(1311) : error C1503: undefined variable "is_distant_horizons_terrain"
0(1312) : error C1503: undefined variable "dhProjectionInverse"
```

**Comment by nvb-uy** [comment]
Don't use optifine

**Comment by nvb-uy** [comment]
Oops my bad I misread it. Please make sure Iris is on the latest version
