### ISSUE TITLE
hysteria crash

### ISSUE THREAD

**Issue by loti1234** [nvb-uy/Hysteria#3]
### What happened?

crashed when turning it on even on startup
[crash log.log](https://github.com/user-attachments/files/16322416/crash.log.log)

### Minecraft Version

1.20.1

### Which shader mod are you using?

Iris

### Shader mod version

oculus-mc1.20.1-1.7.0.jar

### Shader settings

```conf
default
```

**Comment by nvb-uy** [comment]
Look like an issue with AMD drivers, make sure you didn't turn on colored lighting
