### ISSUE TITLE
Armor becomes invisible.

### ISSUE THREAD

**Issue by CDRAGONN44** [nvb-uy/Hysteria#5]
### What happened?

Hello, I had equipped armor in creative, after doing so I went to enable the shaders. When I did so the armor became invisible while also making the lower half of my body invisible as well. Despite being invisible, I could still see the shape of the armor when facing the ocean. It also affects vanilla armor as well as modded ones. Thank you for your time.
![2024-08-01_16 21 46](https://github.com/user-attachments/assets/ca92a34b-6b48-4109-ad6b-8e6e0926158e)

### Minecraft Version

1.19.2

### Which shader mod are you using?

Iris

### Shader mod version

v1.1.0

### Shader settings

```conf
I only used the default balanced profile, however after testing it is still an issue on every one of the default profiles. No settings were changed or modified.
```

**Comment by YeraX7** [comment]
Same in 1.20.1

**Comment by R-udren** [comment]
Same in shader version 1.2.1, Iris

**Comment by R-udren** [comment]
I found fix in [Photon issue](https://github.com/sixthsurge/photon/issues/193#issuecomment-2211701496). This is fault of **Shoulder Surfing Reloaded** mod.
