### ISSUE TITLE
Daytime sky turns to nighttime when looking straight up

### ISSUE THREAD

**Issue by plumprumps** [nvb-uy/Hysteria#6]
### What happened?

The higher up I look during the daytime, the darker the sky gets. When I look straight up, the sky is the nighttime sky. Happens all day every day, but the nighttime does not show day sky.

The below pictures were taken milliseconds apart to show what I mean.

![2024-08-22_16 24 27](https://github.com/user-attachments/assets/0668dbc2-9b95-4042-b811-653d86addbd9)
![2024-08-22_16 24 20](https://github.com/user-attachments/assets/313d0759-2b3a-4a3d-8f84-eeb696c3f79c)

### Minecraft Version

1.20.1

### Which shader mod are you using?

Optifine

### Shader mod version

1.2.1

### Shader settings

```conf
**Using the default Performance settings for Hysteria Shaders, but have tried each default settings profile.

#Thu Aug 22 16:20:14 EDT 2024
SKY_REFLECTIONS=false
shadowMapResolution=1024
TAAU=true
SH_SKYLIGHT=true
ENTITY_SHADOWS=false
TAAU_RENDER_SCALE=0.66
INFO=1
```

**Comment by nvb-uy** [comment]
Optifine issue

**Comment by plumprumps** [comment]
Fixed by uninstalling a couple of mods (Better Fog, the Anomaly). NOT an optifine issue.
